export const MeTypes = {
    RESPONSE_SUCCESS: '@@me/RESPONSE_SUCCESS',
    RESPONSE_ERROR: '@@me/RESPONSE_ERROR',
    RESET_ERROR: '@@me/RESET_ERROR',
    RESET_SUCCESS_UPDATE: '@@me/RESET_SUCCESS_UPDATE',
    RESET_SUCCESS_SUBMIT: '@@me/RESET_SUCCESS_SUBMIT',
    RESET_SUCCESS_APPROVE: '@@me/RESET_SUCCESS_APPROVE',
    RESET_SUCCESS_FEEDBACK: '@@me/RESET_SUCCESS_FEEDBACK',
    RESET_SUCCESS_APPROVE_MULTIPLE: '@@me/RESET_SUCCESS_APPROVE_MULTIPLE',
    RESET_SUCCESS_FEEDBACK_MULTIPLE: '@@me/RESET_SUCCESS_FEEDBACK_MULTIPLE',

    GET_ME_LIST: '@@me/GET_ME_LIST',
    UPDATE_ME: '@@me/UPDATE_ME',
    SUBMIT_ME: '@@me/SUBMIT_ME',
    APPROVE_ME: '@@me/APPROVE_ME',
    FEEDBACK_ME: '@@me/FEEDBACK_ME',
    APPROVE_MULTIPLE_ME: '@@me/APPROVE_MULTIPLE_ME',
    FEEDBACK_MULTIPLE_ME: '@@me/FEEDBACK_MULTIPLE_ME',
};
