const MENU_ITEMS = [
    { key: 'navigation', label: 'Navigation', isTitle: true },
    {
        key: 'dashboards',
        label: 'Dashboards',
        isTitle: false,
        icon: 'uil-home-alt',
        badge: { variant: 'success', text: '1' },
        children: [
            { key: 'ds-analytics', label: 'Analytics', url: '/dashboard/analytics', parentKey: 'dashboards' },
        ],
    },

    { key: 'custom', label: 'Custom', isTitle: true },
    {
        key: 'pages',
        label: 'Pages',
        isTitle: false,
        icon: 'uil-copy-alt',
        children: [
            { key: 'page-profile', label: 'Profile', url: '/pages/profile', parentKey: 'pages' },
            { key: 'page-profile2', label: 'Profile 2', url: '/pages/profile2', parentKey: 'pages' },
            { key: 'page-invoice', label: 'Invoice', url: '/pages/invoice', parentKey: 'pages' },
            { key: 'page-faq', label: 'FAQ', url: '/pages/faq', parentKey: 'pages' },
            { key: 'page-pricing', label: 'Pricing', url: '/pages/pricing', parentKey: 'pages' },
            {
                key: 'page-maintenance',
                label: 'Maintenance',
                url: '/maintenance',
                target: '_blank',
                parentKey: 'pages',
            },
            { key: 'page-error-404', label: 'Error - 404', url: '/error-404', parentKey: 'pages' },
            { key: 'page-error-404-alt', label: 'Error - 404-alt', url: '/pages/error-404-alt', parentKey: 'pages' },
            { key: 'page-error-500', label: 'Error - 500', url: '/error-500', parentKey: 'pages' },
            { key: 'page-starter', label: 'Starter Page', url: '/pages/starter', parentKey: 'pages' },
            { key: 'page-preloader', label: 'With Preloader', url: '/pages/preloader', parentKey: 'pages' },
            { key: 'page-timeline', label: 'Timeline', url: '/pages/timeline', parentKey: 'pages' },
        ],
    },
    {
        key: 'landing',
        label: 'Landing',
        isTitle: false,
        icon: 'uil-globe',
        url: '/landing',
        target: '_blank',
        badge: { variant: 'light-lighten', text: 'New' },
    },

    { key: 'components', label: 'Components', isTitle: true },
    {
        key: 'base-ui',
        label: 'Base UI',
        isTitle: false,
        icon: 'uil-box',
        children: [
            { key: 'base-ui-accordions', label: 'Accordions', url: '/ui/accordions', parentKey: 'base-ui' },
            { key: 'base-ui-alerts', label: 'Alerts', url: '/ui/alerts', parentKey: 'base-ui' },
            { key: 'base-ui-avatars', label: 'Avatars', url: '/ui/avatars', parentKey: 'base-ui' },
            { key: 'base-ui-badges', label: 'Badges', url: '/ui/badges', parentKey: 'base-ui' },
            { key: 'base-ui-breadcrumb', label: 'Breadcrumb', url: '/ui/breadcrumb', parentKey: 'base-ui' },
            { key: 'base-ui-buttons', label: 'Buttons', url: '/ui/buttons', parentKey: 'base-ui' },
            { key: 'base-ui-cards', label: 'Cards', url: '/ui/cards', parentKey: 'base-ui' },
            { key: 'base-ui-carousel', label: 'Carousel', url: '/ui/carousel', parentKey: 'base-ui' },
            { key: 'base-ui-dropdown', label: 'Dropdowns', url: '/ui/dropdowns', parentKey: 'base-ui' },
            { key: 'base-ui-embedvideo', label: 'Embed Video', url: '/ui/embedvideo', parentKey: 'base-ui' },
            { key: 'base-ui-grid', label: 'Grid', url: '/ui/grid', parentKey: 'base-ui' },
            { key: 'base-ui-listgroups', label: 'List Groups', url: '/ui/listgroups', parentKey: 'base-ui' },
            { key: 'base-ui-modals', label: 'Modals', url: '/ui/modals', parentKey: 'base-ui' },
            { key: 'base-ui-notifications', label: 'Notifications', url: '/ui/notifications', parentKey: 'base-ui' },
            { key: 'base-ui-offcanvas', label: 'Offcanvas', url: '/ui/offcanvas', parentKey: 'base-ui' },
            { key: 'base-ui-paginations', label: 'Paginations', url: '/ui/paginations', parentKey: 'base-ui' },
            { key: 'base-ui-popovers', label: 'Popovers', url: '/ui/popovers', parentKey: 'base-ui' },
            { key: 'base-ui-progress', label: 'Progress', url: '/ui/progress', parentKey: 'base-ui' },
            { key: 'base-ui-ribbons', label: 'Ribbons', url: '/ui/ribbons', parentKey: 'base-ui' },
            { key: 'base-ui-spinners', label: 'Spinners', url: '/ui/spinners', parentKey: 'base-ui' },
            { key: 'base-ui-tabs', label: 'Tabs', url: '/ui/tabs', parentKey: 'base-ui' },
            { key: 'base-ui-tooltips', label: 'Tooltips', url: '/ui/tooltips', parentKey: 'base-ui' },
            { key: 'base-ui-typography', label: 'Typography', url: '/ui/typography', parentKey: 'base-ui' },
        ],
    },
    {
        key: 'extended-ui',
        label: 'Extended UI',
        isTitle: false,
        icon: 'uil-package',
        children: [
            { key: 'extended-ui-dragdrop', label: 'Drag and Drop', url: '/ui/dragdrop', parentKey: 'extended-ui' },
            {
                key: 'extended-ui-rangesliders',
                label: 'Range Sliders',
                url: '/ui/rangesliders',
                parentKey: 'extended-ui',
            },
            { key: 'extended-ui-ratings', label: 'Ratings', url: '/ui/ratings', parentKey: 'extended-ui' },
        ],
    },
    { key: 'widgets', label: 'Widgets', isTitle: false, icon: 'uil-layer-group', url: '/ui/widgets' },
    {
        key: 'icons',
        label: 'Icons',
        isTitle: false,
        icon: 'uil-streering',
        children: [
            { key: 'icon-dripicons', label: 'Dripicons', url: '/ui/icons/dripicons', parentKey: 'icons' },
            { key: 'icon-mdiicons', label: 'Material Design', url: '/ui/icons/mdi', parentKey: 'icons' },
            { key: 'icon-unicons', label: 'Unicons', url: '/ui/icons/unicons', parentKey: 'icons' },
        ],
    },
    {
        key: 'forms',
        label: 'Forms',
        isTitle: false,
        icon: 'uil-document-layout-center',
        children: [
            { key: 'form-basic', label: 'Basic Elements', url: '/ui/forms/basic', parentKey: 'forms' },
            { key: 'form-advanced', label: 'Form Advanced', url: '/ui/forms/advanced', parentKey: 'forms' },
            { key: 'form-validation', label: 'Validation', url: '/ui/forms/validation', parentKey: 'forms' },
            { key: 'form-wizard', label: 'Wizard', url: '/ui/forms/wizard', parentKey: 'forms' },
            { key: 'form-upload', label: 'File Upload', url: '/ui/forms/upload', parentKey: 'forms' },
            { key: 'form-editors', label: 'Editors', url: '/ui/forms/editors   ', parentKey: 'forms' },
        ],
    },
    {
        key: 'charts',
        label: 'Charts',
        isTitle: false,
        icon: 'uil-chart',
        children: [
            { key: 'chart-apex', label: 'Apex Charts', url: '/ui/charts/apex', parentKey: 'charts' },
            { key: 'chart-brite', label: 'Brite Charts', url: '/ui/charts/brite', parentKey: 'charts' },
            { key: 'chart-chartjs', label: 'Chartjs', url: '/ui/charts/chartjs', parentKey: 'charts' },
        ],
    },
    {
        key: 'tables',
        label: 'Tables',
        isTitle: false,
        icon: 'uil-table',
        children: [
            { key: 'table-basic', label: 'Basic Tables', url: '/ui/tables/basic', parentKey: 'tables' },
            { key: 'table-advanced', label: 'Advanced Tables', url: '/ui/tables/advanced', parentKey: 'tables' },
        ],
    },
    {
        key: 'maps',
        label: 'Maps',
        isTitle: false,
        icon: 'uil-location-point',
        children: [
            { key: 'maps-googlemaps', label: 'Google Maps', url: '/ui/googlemaps', parentKey: 'maps' },
            { key: 'maps-vectormaps', label: 'Vector Maps', url: '/ui/vectormaps', parentKey: 'maps' },
        ],
    },
    {
        key: 'menu-levels',
        label: 'Menu Levels',
        isTitle: false,
        icon: 'uil-folder-plus',
        children: [
            {
                key: 'menu-levels-1-1',
                label: 'Level 1.1',
                url: '/',
                parentKey: 'menu-levels',
                children: [
                    {
                        key: 'menu-levels-2-1',
                        label: 'Level 2.1',
                        url: '/',
                        parentKey: 'menu-levels-1-1',
                        children: [
                            { key: 'menu-levels-3-1', label: 'Level 3.1', url: '/', parentKey: 'menu-levels-2-1' },
                            { key: 'menu-levels-3-2', label: 'Level 3.2', url: '/', parentKey: 'menu-levels-2-1' },
                        ],
                    },
                    { key: 'menu-levels-2-2', label: 'Level 2.2', url: '/', parentKey: 'menu-levels-1-1' },
                ],
            },
            { key: 'menu-levels-1-2', label: 'Level 1.2', url: '/', parentKey: 'menu-levels' },
        ],
    },
];

export default MENU_ITEMS;
