export const commentActionTypes = {
    COMMENT_CONTENT: '@@comment/COMMENT_CONTENT',
    REGISTER_GOOGLE: '@@comment/REGISTER_GOOGLE',
    COMMENT_BASIC: '@@comment/COMMENT_BASIC',
    CHANGE_SIDEBAR_TYPE: '@@comment/CHANGE_SIDEBAR_TYPE',

    TOGGLE_RIGHT_SIDEBAR: '@@comment/TOGGLE_RIGHT_SIDEBAR',
    SHOW_RIGHT_SIDEBAR: '@@comment/SHOW_RIGHT_SIDEBAR',
    HIDE_RIGHT_SIDEBAR: '@@comment/HIDE_RIGHT_SIDEBAR',
};

