export const postsListActionTypes = {
    POSTS_LIST: '@@postsList/POSTS_LIST',
    POSTS_DETAIL: '@@postsList/POSTS_DETAIL',
    REGISTER_GOOGLE: '@@postsList/REGISTER_GOOGLE',
    REGISTER_BASIC: '@@postsList/REGISTER_BASIC',
    CHANGE_SIDEBAR_TYPE: '@@postsList/CHANGE_SIDEBAR_TYPE',

    FETCH_DATA_DETAIL_SUCCESS: '@@postsList/FETCH_DATA_DETAIL_SUCCESS',
    FETCH_DATA_DETAIL_ERROR: '@@postsList/FETCH_DATA_DETAIL_ERROR',
};
