export const MeTypes = {
    UPDATE_PROFILE: '@@me/UPDATE_PROFILE',
    UPDATE_POSTUSER: '@@me/UPDATE_POSTUSER',
    UPDATE_COMPARE: '@@me/UPDATE_COMPARE',
    
    CHANGE_PASSWORD:'@@me/CHANGE_PASSWORD',

    RESPONSE_ERROR:'@@me/RESPONSE_ERROR',
    RESPONSE_SUCCESS: '@@me/RESPONSE_SUCCESS'


};
