export const MeTypes = {
    UPDATE_PROFILE: '@@me/UPDATE_PROFILE',
    UPDATE_POSTUSER: '@@me/UPDATE_POSTUSER',
    UPDATE_COMPARE: '@@me/UPDATE_COMPARE',
    FORGOT_PASSWORD:'@@me/FORGOT_PASSWORD',
    
    RESPONSE_SUCCESS:'@@me/RESPONSE_SUCCESS',
    RESPONSE_ERROR:'@@me/RESPONSE_ERROR'
};
